### ISSUE TITLE
PCAP errors on unknown TCP options - place try..catch around packet.decode

### ISSUE THREAD

**Issue by pandel** [sj82516/turn-monitor#1]
Hi!

If there are unusual TCP packet options floating around your network, pcap errors out.

https://github.com/node-pcap/node_pcap/issues/240

You should put a try..catch block around

https://github.com/sj82516/turn-monitor/blob/27c3d3a0c9e7cb0577fdb52f6c04e0ec5277f667/capturePacket.ts#L52

so that your service won't stop, but simply logs the error and continues.

Regards,
Holger

**Comment by yuanchieh-at** [comment]
Thanks for your report! I would fix it soon

**Comment by sj82516** [comment]
Thanks for your report! I would fix it ASAP

Holger Pandel ***@***.***> 於 2022年1月12日 週三 上午7:50寫道：

**Comment by sj82516** [comment]
Fixed
